"""
GenVM deploys a single file with no access to sibling modules, so the
local imports that work under pytest fail on chain. This inlines
agreement.py and judgment.py into quorum.py to produce
contracts/quorum_bundle.py, which is what gets deployed.

Run: python deploy/build_bundle.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
OUT = CONTRACTS / "quorum_bundle.py"

DEPENDS = (
    '# { "Depends": "py-genlayer:'
    '1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }'
)

DROP = {
    "import json",
    "import re",
    "from dataclasses import dataclass, field",
    "from dataclasses import dataclass",
    "from typing import Any",
    "from genlayer import *",
}

MULTILINE_STARTS = (
    "from contracts.agreement import (",
    "from contracts.judgment import (",
)

SINGLE_LINE_LOCAL = ("from contracts.agreement import", "from contracts.judgment import")


def strip_docstring(source: str) -> str:
    lines = source.split("\n")
    i = 0
    while i < len(lines) and lines[i].strip() == "":
        i += 1
    if i < len(lines) and lines[i].lstrip().startswith('"""'):
        first = lines[i]
        i += 1
        if first.count('"""') < 2:
            while i < len(lines) and '"""' not in lines[i]:
                i += 1
            i += 1
    return "\n".join(lines[i:])


def strip_imports(source: str) -> str:
    out = []
    skipping = False
    for line in source.split("\n"):
        s = line.strip()
        if skipping:
            if s.endswith(")"):
                skipping = False
            continue
        if s in MULTILINE_STARTS:
            skipping = True
            continue
        if s in DROP:
            continue
        if any(s.startswith(p) for p in SINGLE_LINE_LOCAL):
            continue
        out.append(line)
    return "\n".join(out)


def body_of(name: str, drop_depends: bool = False) -> str:
    src = (CONTRACTS / name).read_text(encoding="utf-8")
    if drop_depends:
        lines = src.split("\n")
        assert lines[0].strip().startswith('# { "Depends"'), name
        src = "\n".join(lines[1:])
    return strip_imports(strip_docstring(src)).strip("\n")


def main() -> None:
    sections = [
        DEPENDS,
        (
            '"""\n'
            "QUORUM, bundled for deployment.\n\n"
            "Generated by deploy/build_bundle.py from agreement.py,\n"
            "judgment.py, and quorum.py. Do not hand-edit; edit those\n"
            "and regenerate. This file exists only because GenVM deploys a\n"
            "single file with no access to sibling local modules.\n"
            '"""'
        ),
        "import json",
        "import re",
        "from dataclasses import dataclass, field",
        "from typing import Any",
        "",
        "from genlayer import *",
        "",
        body_of("agreement.py"),
        body_of("judgment.py"),
        body_of("quorum.py", drop_depends=True),
    ]
    bundle = "\n\n\n".join(s.strip("\n") for s in sections) + "\n"
    OUT.write_text(bundle, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} ({len(bundle)} bytes)")


if __name__ == "__main__":
    main()
