# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }


"""
QUORUM, bundled for deployment.

Generated by deploy/build_bundle.py from agreement.py,
judgment.py, and quorum.py. Do not hand-edit; edit those
and regenerate. This file exists only because GenVM deploys a
single file with no access to sibling local modules.
"""


import json


import re


from dataclasses import dataclass, field


from typing import Any





from genlayer import *





# Two numbers count as the same claim when they are within this fraction of
# each other. Sources round differently and report at different precisions,
# so demanding exact equality would manufacture disagreement out of
# journalistic convention rather than substance.
_RELATIVE_TOLERANCE = 0.05

# Percentages are compared in absolute points as well, because a relative
# tolerance behaves badly near zero: 0.1% and 0.2% differ by 100% relatively
# while being the same claim in substance.
_ABSOLUTE_POINT_TOLERANCE = 1.0

_NUMBER_WORDS = {
    "zero": 0.0, "one": 1.0, "two": 2.0, "three": 3.0, "four": 4.0,
    "five": 5.0, "six": 6.0, "seven": 7.0, "eight": 8.0, "nine": 9.0,
    "ten": 10.0, "eleven": 11.0, "twelve": 12.0, "half": 0.5,
}

_SCALE_WORDS = {
    "hundred": 1e2, "thousand": 1e3, "k": 1e3,
    "million": 1e6, "m": 1e6, "mn": 1e6,
    "billion": 1e9, "bn": 1e9, "b": 1e9,
    "trillion": 1e12, "tn": 1e12,
}

_AFFIRMATIVE = {"yes", "true", "correct", "confirmed", "affirmative", "y"}
_NEGATIVE = {"no", "false", "incorrect", "denied", "negative", "n"}

# Answers that mean the source did not actually say. Treated as abstention
# rather than disagreement, because a source that is silent on a claim is
# not evidence against it.
_NO_ANSWER = {
    "", "unknown", "not stated", "notstated", "unclear", "none",
    "not found", "notfound", "n/a", "na", "not mentioned", "notmentioned",
    "no answer", "noanswer", "unavailable",
}

KIND_NUMERIC = "numeric"
KIND_PERCENT = "percent"
KIND_BOOLEAN = "boolean"
KIND_DATE = "date"
KIND_TEXT = "text"
KIND_ABSTAIN = "abstain"


@dataclass
class Extracted:
    """What one source was found to say about the claim."""

    source: str
    raw: str
    kind: str
    value: float = 0.0
    text: str = ""


@dataclass
class AgreementResult:
    verdict: str
    kind: str
    consensus_value: str
    agreeing: list = field(default_factory=list)
    dissenting: list = field(default_factory=list)
    abstaining: list = field(default_factory=list)
    needs_model: bool = False

    @property
    def agreement_ratio_percent(self) -> int:
        """
        Share of sources that actually answered and agreed. Abstentions are
        excluded from the denominator: three sources agreeing out of three
        that answered is not weakened by a fourth that was silent.
        """
        answered = len(self.agreeing) + len(self.dissenting)
        if answered == 0:
            return 0
        return (len(self.agreeing) * 100) // answered


def _clean(raw: str) -> str:
    return re.sub(r"\s+", " ", (raw or "").strip().lower())


def classify(source: str, raw: str) -> Extracted:
    """
    Work out what kind of answer a source gave, so the right comparison
    rule applies. Order matters: percentages are checked before bare
    numbers, because "40%" is both and the percent reading is the specific
    one.
    """
    cleaned = _clean(raw)

    if cleaned in _NO_ANSWER:
        return Extracted(source=source, raw=raw, kind=KIND_ABSTAIN)

    percent = _parse_percent(cleaned)
    if percent is not None:
        return Extracted(source, raw, KIND_PERCENT, value=percent)

    date = _parse_date(cleaned)
    if date is not None:
        return Extracted(source, raw, KIND_DATE, value=date)

    boolean = _parse_boolean(cleaned)
    if boolean is not None:
        return Extracted(source, raw, KIND_BOOLEAN, value=boolean)

    number = _parse_number(cleaned)
    if number is not None:
        return Extracted(source, raw, KIND_NUMERIC, value=number)

    return Extracted(source, raw, KIND_TEXT, text=cleaned)


def _parse_percent(cleaned: str):
    match = re.search(r"(-?[\d,]*\.?\d+)\s*(?:%|percent|per cent|pct)", cleaned)
    if match:
        try:
            return float(match.group(1).replace(",", ""))
        except ValueError:
            return None
    # "two in five" and "1 in 4" are percentages wearing a different hat.
    ratio = re.search(r"\b(\w+|\d+)\s+in\s+(\w+|\d+)\b", cleaned)
    if ratio:
        num = _word_or_digit(ratio.group(1))
        den = _word_or_digit(ratio.group(2))
        if num is not None and den not in (None, 0):
            return (num / den) * 100.0
    return None


def _word_or_digit(token: str):
    token = token.strip()
    if token in _NUMBER_WORDS:
        return _NUMBER_WORDS[token]
    try:
        return float(token.replace(",", ""))
    except ValueError:
        return None


def _parse_range(cleaned: str):
    """
    A stated range such as "between 17 and 21 million" or "13 to 15m".

    Ranges are read as their midpoint. A source giving a range is making a
    less precise claim than one giving a figure, but it is still a claim,
    and the tolerance in _values_agree is what decides whether it matches
    a neighbour. Discarding the range and keeping only its first number
    would be worse than either: "between 17 and 21 million" would become
    the number 17, which is not a population and would disagree with
    everything by a factor of a million.
    """
    m = re.search(
        r"(-?[\d,]*\.?\d+)\s*(?:to|and|through|[-])\s*(-?[\d,]*\.?\d+)"
        r"\s*(hundred|thousand|million|billion|trillion|k|m|mn|bn|b|tn)?\b",
        cleaned,
    )
    if not m:
        return None
    try:
        low = float(m.group(1).replace(",", ""))
        high = float(m.group(2).replace(",", ""))
    except ValueError:
        return None
    # A trailing scale word applies to both ends: "17 and 21 million" is
    # not seventeen and twenty-one million.
    scale = _SCALE_WORDS[m.group(3)] if m.group(3) else 1.0
    return ((low + high) / 2.0) * scale


def _parse_number(cleaned: str):
    # Ranges first: the range pattern contains bare numbers, so a plain
    # number search would match the low end and silently drop the rest.
    ranged = _parse_range(cleaned)
    if ranged is not None:
        return ranged

    # A bare number, optionally with a scale word: "3.2 million", "40k".
    match = re.search(
        r"(-?[\d,]*\.?\d+)\s*(hundred|thousand|million|billion|trillion|k|m|mn|bn|b|tn)?\b",
        cleaned,
    )
    if match:
        try:
            value = float(match.group(1).replace(",", ""))
        except ValueError:
            return None
        scale = match.group(2)
        if scale:
            value *= _SCALE_WORDS[scale]
        return value

    for word, value in _NUMBER_WORDS.items():
        if re.search(rf"\b{word}\b", cleaned):
            scale_match = re.search(
                r"\b(hundred|thousand|million|billion|trillion)\b", cleaned
            )
            return value * (_SCALE_WORDS[scale_match.group(1)] if scale_match else 1.0)
    return None


def _parse_boolean(cleaned: str):
    first = cleaned.split(" ")[0].strip(".,;:!")
    if first in _AFFIRMATIVE:
        return 1.0
    if first in _NEGATIVE:
        return 0.0
    return None


def _parse_date(cleaned: str):
    """
    Dates become a sortable integer so comparison is exact. Only
    unambiguous formats are accepted; 03/04/2026 is deliberately not
    parsed, because it means March in one country and April in another and
    guessing would silently invent agreement or disagreement.
    """
    iso = re.search(r"\b(\d{4})-(\d{2})-(\d{2})\b", cleaned)
    if iso:
        return float(f"{iso.group(1)}{iso.group(2)}{iso.group(3)}")

    months = {
        "january": 1, "february": 2, "march": 3, "april": 4, "may": 5,
        "june": 6, "july": 7, "august": 8, "september": 9, "october": 10,
        "november": 11, "december": 12,
        "jan": 1, "feb": 2, "mar": 3, "apr": 4, "jun": 6, "jul": 7,
        "aug": 8, "sep": 9, "sept": 9, "oct": 10, "nov": 11, "dec": 12,
    }
    named = re.search(
        r"\b(\d{1,2})\s+([a-z]+)\s+(\d{4})\b|\b([a-z]+)\s+(\d{1,2}),?\s+(\d{4})\b",
        cleaned,
    )
    if named:
        if named.group(2):
            day, month_name, year = named.group(1), named.group(2), named.group(3)
        else:
            month_name, day, year = named.group(4), named.group(5), named.group(6)
        month = months.get(month_name)
        if month:
            return float(f"{year}{month:02d}{int(day):02d}")
    return None


def _values_agree(kind: str, a: float, b: float) -> bool:
    if kind == KIND_BOOLEAN:
        return a == b
    if kind == KIND_DATE:
        return a == b
    if kind == KIND_PERCENT:
        if abs(a - b) <= _ABSOLUTE_POINT_TOLERANCE:
            return True
        return _within_relative(a, b)
    return _within_relative(a, b)


def _within_relative(a: float, b: float) -> bool:
    if a == b:
        return True
    largest = max(abs(a), abs(b))
    if largest == 0:
        return True
    return abs(a - b) / largest <= _RELATIVE_TOLERANCE


def assess(extracted: list) -> AgreementResult:
    """
    Decide whether the sources agree, and record exactly who did not.

    The dissent record is the output that matters. An oracle that returns
    only a value hides the one fact a caller needs in order to weigh it: a
    number three sources agree on is a different thing from the same number
    with two sources actively contradicting it.
    """
    answered = [e for e in extracted if e.kind != KIND_ABSTAIN]
    abstaining = [e.source for e in extracted if e.kind == KIND_ABSTAIN]

    if not answered:
        return AgreementResult(
            verdict="no_data",
            kind=KIND_ABSTAIN,
            consensus_value="",
            abstaining=abstaining,
        )

    kinds = {e.kind for e in answered}

    # Mixed kinds, or prose, cannot be settled by arithmetic. Hand it on.
    if len(kinds) > 1 or kinds == {KIND_TEXT}:
        return AgreementResult(
            verdict="needs_judgment",
            kind=KIND_TEXT if kinds == {KIND_TEXT} else "mixed",
            consensus_value="",
            abstaining=abstaining,
            needs_model=True,
        )

    kind = answered[0].kind

    # The majority cluster wins. Each answer is scored by how many others
    # agree with it, rather than trusting the first source to reply, which
    # would make the verdict depend on source ordering.
    best = None
    best_agreeing = []
    for candidate in answered:
        agreeing = [e for e in answered if _values_agree(kind, candidate.value, e.value)]
        if best is None or len(agreeing) > len(best_agreeing):
            best = candidate
            best_agreeing = agreeing

    dissenting = [e for e in answered if e not in best_agreeing]

    if not dissenting:
        verdict = "corroborated"
    elif len(best_agreeing) > len(dissenting):
        verdict = "majority"
    else:
        verdict = "contested"

    return AgreementResult(
        verdict=verdict,
        kind=kind,
        consensus_value=best.raw,
        agreeing=[e.source for e in best_agreeing],
        dissenting=[e.source for e in dissenting],
        abstaining=abstaining,
    )


# Answer shapes the extractor is allowed to return, so a caller can branch
# without pattern matching prose.
ANSWER_FOUND = "found"
ANSWER_NOT_STATED = "not_stated"
ANSWER_UNREADABLE = "unreadable"

_EXTRACTION_PROMPT = """You are reading ONE document to find what it says about a
specific claim. You have not seen any other document, and you must not guess
at what other sources might say.

Claim to check:
{claim}

Document:
```document
{document}
```

Answer only from this document. If it does not address the claim, say so
rather than inferring a likely answer; a document that is silent is more
useful to record as silent than to fill in.

Respond using ONLY this JSON format:
{{
"status": "found" | "not_stated" | "unreadable",
"answer": "the shortest exact answer the document supports, or empty",
"quote": "the sentence you took it from, or empty"
}}
Use "found" only when the document directly supports an answer. Use
"not_stated" when the document is readable but does not address the claim.
Use "unreadable" when the document is an error page, a paywall, or is
otherwise not the content it should be. Keep "answer" short: a number, a
date, a yes or no, or one clause. Respond with JSON only.
"""

_RECONCILIATION_PROMPT = """Several sources answered the same question in prose,
so they cannot be compared as numbers. Decide which of them are making the
same claim.

Question:
{claim}

Answers:
{answers}

Two answers agree when they assert the same thing about the world, even if
worded differently. They disagree when one contradicts the other. Different
levels of detail are not disagreement; a contradiction is.

Respond using ONLY this JSON format:
{{
"consensus": "the claim the largest group of answers supports, or empty",
"agreeing": [answer numbers that support it],
"dissenting": [answer numbers that contradict it]
}}
Every answer number must appear in exactly one of the two lists. Use the
numbers exactly as labelled. Respond with JSON only.
"""


@dataclass
class Extraction:
    status: str
    answer: str = ""
    quote: str = ""


@dataclass
class Reconciliation:
    consensus: str = ""
    agreeing: list = None
    dissenting: list = None

    def __post_init__(self):
        if self.agreeing is None:
            self.agreeing = []
        if self.dissenting is None:
            self.dissenting = []


def build_extraction_prompt(claim: str, document: str, max_chars: int = 6000) -> str:
    """
    One claim, one document. `max_chars` truncates very long pages: a
    prompt the model silently truncates itself would drop the end of the
    document without saying so, and an answer drawn from a page the model
    only half read is worse than an honest "not stated".
    """
    body = (document or "").strip()
    if len(body) > max_chars:
        body = body[:max_chars] + "\n[document truncated]"
    return _EXTRACTION_PROMPT.format(claim=(claim or "").strip(), document=body)


def build_reconciliation_prompt(claim: str, answers: list) -> str:
    numbered = "\n".join(
        f"Answer {i}: {a}" for i, a in enumerate(answers, start=1)
    )
    return _RECONCILIATION_PROMPT.format(claim=(claim or "").strip(), answers=numbered)


def _decode(raw: Any):
    if isinstance(raw, dict):
        return raw
    text = (raw or "").strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.lower().startswith("json"):
            text = text[4:]
    try:
        return json.loads(text.strip())
    except json.JSONDecodeError:
        return None


def parse_extraction(raw: Any) -> Extraction:
    """
    Unparseable output becomes "unreadable" rather than an answer.

    A model that returns broken JSON has told us nothing about the
    document, and inventing an answer from that would put a fabricated
    data point into a corroboration count. Recording it as unreadable
    keeps the source out of the tally instead, which is the honest effect
    of not knowing.
    """
    data = _decode(raw)
    if not isinstance(data, dict):
        return Extraction(status=ANSWER_UNREADABLE)

    status = str(data.get("status", "")).strip().lower()
    if status not in (ANSWER_FOUND, ANSWER_NOT_STATED, ANSWER_UNREADABLE):
        status = ANSWER_UNREADABLE

    answer = str(data.get("answer", "") or "").strip()
    # A "found" with nothing in it is not a finding.
    if status == ANSWER_FOUND and not answer:
        status = ANSWER_NOT_STATED

    return Extraction(
        status=status,
        answer=answer if status == ANSWER_FOUND else "",
        quote=str(data.get("quote", "") or "").strip(),
    )


def parse_reconciliation(raw: Any, answer_count: int) -> Reconciliation:
    """
    Validate the returned indices against the list actually sent.

    Same reasoning as the extraction guard: an index pointing at an answer
    that was never shown cannot be resolved to a real source, and guessing
    which one was meant would attribute a position to a source that never
    took it. Out of range entries are dropped, and anything unaccounted
    for is treated as dissent, because silence from the reconciler is not
    evidence of agreement.
    """
    data = _decode(raw)
    if not isinstance(data, dict):
        return Reconciliation(dissenting=list(range(answer_count)))

    def valid(key):
        out = []
        for item in data.get(key, []) or []:
            try:
                idx = int(item) - 1
            except (TypeError, ValueError):
                continue
            if 0 <= idx < answer_count:
                out.append(idx)
        return sorted(set(out))

    agreeing = valid("agreeing")
    dissenting = [i for i in valid("dissenting") if i not in agreeing]

    accounted = set(agreeing) | set(dissenting)
    unaccounted = [i for i in range(answer_count) if i not in accounted]
    dissenting = sorted(dissenting + unaccounted)

    return Reconciliation(
        consensus=str(data.get("consensus", "") or "").strip(),
        agreeing=agreeing,
        dissenting=dissenting,
    )


# Each source costs a fetch and a prompt on every validator, so the cap is
# a real cost control rather than a formality. Corroboration also stops
# paying for itself well before this: the difference between three sources
# and four is large, between eleven and twelve is noise.
_MAX_SOURCES = 8

# Quotes are stored so a reader can check the contract's work, but storage
# is replicated and kept indefinitely, so they are truncated rather than
# kept whole. A sentence is enough to find the passage in the source.
_MAX_QUOTE = 240


@allow_storage
@dataclass
class SourceAnswer:
    url: str
    status: str
    answer: str
    quote: str


@allow_storage
@dataclass
class CheckRecord:
    claim: str
    verdict: str
    consensus_value: str
    agreement_percent: u256
    sources_answered: u256
    sources_dissenting: u256
    sources_silent: u256
    answers: DynArray[SourceAnswer]
    dissenting: DynArray[str]
    settled_by: str
    checked_by: Address


class Quorum(gl.Contract):
    checks: TreeMap[str, CheckRecord]
    # A TreeMap cannot be walked from outside the contract, so an archive of
    # past checks would be unreadable without keeping the keys in order as
    # well. Insertion order is the useful order here: it is the order the
    # checks were actually settled in.
    ids: DynArray[str]

    def __init__(self):
        pass

    @gl.public.write
    def check(self, check_id: str, claim: str, sources: list) -> dict:
        """
        Read every source, decide whether they agree, and store the result
        along with who dissented.

        `sources` should be archived or revision-pinned URLs. A live page
        that changes between two validators fetching it produces a
        disagreement about the page rather than about the claim, and the
        transaction fails for a reason unrelated to the question asked.
        """
        key = check_id.strip().lower()
        if key in self.checks:
            raise gl.vm.UserError(f"already checked: {key}")

        urls = [str(u).strip() for u in (sources or []) if str(u).strip()]
        if len(urls) < 2:
            raise gl.vm.UserError(
                "corroboration needs at least two sources; one source is a "
                "quotation, not a corroboration"
            )
        if len(urls) > _MAX_SOURCES:
            raise gl.vm.UserError(f"at most {_MAX_SOURCES} sources per check")

        claim_text = claim.strip()

        def leader_fn():
            # One fetch and one prompt per source, each prompt seeing only
            # its own document. Reading them together would let a confident
            # source colour an ambiguous one and manufacture agreement.
            found = []
            for url in urls:
                try:
                    page = gl.nondet.web.render(url, mode="text")
                except Exception:
                    found.append(
                        {"url": url, "status": "unreadable", "answer": "", "quote": ""}
                    )
                    continue
                raw = gl.nondet.exec_prompt(
                    build_extraction_prompt(claim_text, page), response_format="json"
                )
                got = parse_extraction(raw)
                found.append(
                    {
                        "url": url,
                        "status": got.status,
                        "answer": got.answer,
                        "quote": got.quote[:_MAX_QUOTE],
                    }
                )

            # Classification and agreement are deterministic, and are run
            # in here so the verdict itself is part of what consensus
            # covers rather than something each node derives afterwards.
            classified = [
                classify(f["url"], f["answer"] if f["status"] == ANSWER_FOUND else "")
                for f in found
            ]
            verdict = assess(classified)

            return {
                "found": found,
                "verdict": verdict.verdict,
                "value": verdict.consensus_value,
                "agreeing": verdict.agreeing,
                "dissenting": verdict.dissenting,
                "abstaining": verdict.abstaining,
                "percent": verdict.agreement_ratio_percent,
                "needs_model": verdict.needs_model,
            }

        def validator_fn(leaders_res) -> bool:
            if not isinstance(leaders_res, gl.vm.Return):
                return False
            leader = leaders_res.calldata
            mine = leader_fn()

            # Compare decisions, not prose. Two models reading the same
            # page will write "40 percent" and "40%", and rejecting the
            # leader over that would fail every check that ever ran. What
            # must match is what a caller acts on: the verdict, and which
            # sources were counted as dissenting or silent.
            if mine["verdict"] != leader["verdict"]:
                return False
            if sorted(mine["dissenting"]) != sorted(leader["dissenting"]):
                return False
            return sorted(mine["abstaining"]) == sorted(leader["abstaining"])

        result = gl.vm.run_nondet_unsafe(leader_fn, validator_fn)

        verdict = result["verdict"]
        value = result["value"]
        agreeing = list(result["agreeing"])
        dissenting = list(result["dissenting"])
        settled_by = "arithmetic"

        if result["needs_model"]:
            value, agreeing, dissenting = self._reconcile(claim_text, result["found"])
            answered = len(agreeing) + len(dissenting)
            if not answered:
                verdict = "no_data"
            elif not dissenting:
                verdict = "corroborated"
            elif len(agreeing) > len(dissenting):
                verdict = "majority"
            else:
                verdict = "contested"
            settled_by = "judgment"

        answered = len(agreeing) + len(dissenting)
        percent = (len(agreeing) * 100) // answered if answered else 0

        record = CheckRecord(
            claim=claim_text,
            verdict=verdict,
            consensus_value=value,
            agreement_percent=percent,
            sources_answered=answered,
            sources_dissenting=len(dissenting),
            sources_silent=len(result["abstaining"]),
            answers=[
                SourceAnswer(
                    url=f["url"],
                    status=f["status"],
                    answer=f["answer"],
                    quote=f["quote"],
                )
                for f in result["found"]
            ],
            dissenting=sorted(dissenting),
            settled_by=settled_by,
            checked_by=gl.message.sender_address,
        )
        self.checks[key] = record
        self.ids.append(key)
        return _as_dict(record)

    def _reconcile(self, claim: str, found: list) -> tuple:
        """
        Ask the model which prose answers are making the same claim.

        Only reached when arithmetic could not settle it, which means the
        answers are sentences rather than numbers. The model is given the
        answers alone, never the source URLs, because which outlet said
        something should not influence whether it agrees with another.
        """
        answered = [f for f in found if f["status"] == ANSWER_FOUND and f["answer"]]
        if not answered:
            return "", [], []

        texts = [f["answer"] for f in answered]

        def leader_fn():
            raw = gl.nondet.exec_prompt(
                build_reconciliation_prompt(claim, texts), response_format="json"
            )
            got = parse_reconciliation(raw, len(texts))
            return {
                "consensus": got.consensus,
                "agreeing": got.agreeing,
                "dissenting": got.dissenting,
            }

        def validator_fn(leaders_res) -> bool:
            if not isinstance(leaders_res, gl.vm.Return):
                return False
            leader = leaders_res.calldata
            mine = leader_fn()
            # The split is the decision; the summary sentence may vary.
            return sorted(mine["agreeing"]) == sorted(leader["agreeing"])

        out = gl.vm.run_nondet_unsafe(leader_fn, validator_fn)
        return (
            out["consensus"],
            [answered[i]["url"] for i in out["agreeing"]],
            [answered[i]["url"] for i in out["dissenting"]],
        )

    @gl.public.view
    def get_check(self, check_id: str) -> dict:
        return _as_dict(self.checks[check_id.strip().lower()])

    @gl.public.view
    def verdict_of(self, check_id: str) -> str:
        """Just the verdict, for callers that only branch on it."""
        return self.checks[check_id.strip().lower()].verdict

    @gl.public.view
    def is_checked(self, check_id: str) -> bool:
        return check_id.strip().lower() in self.checks

    @gl.public.view
    def check_ids(self) -> list:
        """Every check this contract has settled, oldest first."""
        return [cid for cid in self.ids]

    @gl.public.view
    def count(self) -> int:
        return len(self.ids)

    @gl.public.view
    def summaries(self) -> list:
        """
        Enough of every check to render an index, in one call.

        Reading the archive as one call per id would be N round trips to
        list N rows, and the quotes and per-source answers are most of the
        payload while being none of what an index shows. This returns the
        verdict line only; the full record is one `get_check` away.
        """
        out = []
        for cid in self.ids:
            record = self.checks[cid]
            out.append(
                {
                    "check_id": cid,
                    "claim": record.claim,
                    "verdict": record.verdict,
                    "consensus_value": record.consensus_value,
                    "agreement_percent": record.agreement_percent,
                    "sources_answered": record.sources_answered,
                    "sources_dissenting": record.sources_dissenting,
                    "sources_silent": record.sources_silent,
                    "settled_by": record.settled_by,
                }
            )
        return out


def _as_dict(record: CheckRecord) -> dict:
    return {
        "claim": record.claim,
        "verdict": record.verdict,
        "consensus_value": record.consensus_value,
        "agreement_percent": record.agreement_percent,
        "sources_answered": record.sources_answered,
        "sources_dissenting": record.sources_dissenting,
        "sources_silent": record.sources_silent,
        "answers": [
            {"url": a.url, "status": a.status, "answer": a.answer, "quote": a.quote}
            for a in record.answers
        ],
        "dissenting": list(record.dissenting),
        "settled_by": record.settled_by,
        "checked_by": record.checked_by.as_hex,
    }
